<a href="https://colab.research.google.com/github/Jawakar-7/Natural-Language-Processing-Specialization-Coursera/blob/main/TensorflowBasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Tensor Flow

 A tensor is a multi-dimensional array&TensorFlow is an open-source software library for building neural networks. Google Brain team was the one who built it and it is the most popular deep learning library in the market today.

In [1]:
import tensorflow as tf
print(tf.__version__)

2.12.0


Creating a Constant Tensor

In [ ]:
a=tf.constant([
 [   [1,2,4],
    [1,2,5],
    [1,2,33]
],[ [1,2,4],
    [1,2,5],
    [1,2,33]],[ [1,2,4],
    [1,2,5],
    [1,2,33]]])

In [ ]:
a

<tf.Tensor: shape=(3, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  4],
        [ 1,  2,  5],
        [ 1,  2, 33]],

       [[ 1,  2,  4],
        [ 1,  2,  5],
        [ 1,  2, 33]],

       [[ 1,  2,  4],
        [ 1,  2,  5],
        [ 1,  2, 33]]], dtype=int32)>

Four Dimensional Tensors of zeros

In [ ]:
_4dimtens=tf.zeros([4,3,2,3])

In [ ]:
_4dimtens

<tf.Tensor: shape=(4, 3, 2, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]],


       [[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>

#### Creating Random Values
Let’s create a tensor with random values. There are two common ways you can do this: generate a normal distribution of data or a uniform distribution of data.

In [3]:
seed=tf.random.Generator.from_seed(33)
norm_dist=seed.normal(shape=(2,3))
print(norm_dist)
uni_dist=seed.uniform(shape=(3,3))
print(uni_dist)

tf.Tensor(
[[-0.1589871   1.302304    0.9592239 ]
 [ 0.85874265 -1.5181769   1.4020647 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.02675951 0.5285536  0.42530107]
 [0.67171764 0.64924705 0.13024127]
 [0.40005922 0.30875564 0.8012408 ]], shape=(3, 3), dtype=float32)


Let’s look at converting NumPy arrays into tensors.

In [15]:
import numpy as np
var=np.arange(1,40,2,dtype=np.int16)
print(var)
var.shape

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39]


(20,)

In [18]:
var1=tf.constant(var,shape=[2,10])
print(var1)

tf.Tensor(
[[ 1  3  5  7  9 11 13 15 17 19]
 [21 23 25 27 29 31 33 35 37 39]], shape=(2, 10), dtype=int16)


### Reshape & Transpose

To reshape, we use the tf.reshape function. To transpose, we use the tf.transpose function. If you don't know what a transpose is, it's converting rows into columns and columns into rows.

In [24]:
var2=tf.reshape(var1,[4,5])
print(var2)

tf.Tensor(
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]], shape=(4, 5), dtype=int16)


In [25]:
var2=tf.transpose(var2)
print(var2)

tf.Tensor(
[[ 1 11 21 31]
 [ 3 13 23 33]
 [ 5 15 25 35]
 [ 7 17 27 37]
 [ 9 19 29 39]], shape=(5, 4), dtype=int16)
